/**
 * Central Asset Manifest
 * 
 * Tracks all logical assets for the fantasy MMO/strategy world with
 * accurate licensing, source attribution, format, status, and technical metrics.
 * 
 * Verified against real 3D model files in /public/assets/medieval/
 * Source: KayKit Medieval Hexagon Pack & Adventurers Character Pack by Kay Lousberg
 * License: CC0 1.0 Universal (Public Domain)
 */

import { AssetMetadata } from './types';

export const ASSET_MANIFEST: Record<string, AssetMetadata> = {
  // ==========================================================================
  // 1. BUILDINGS (REAL 3D ASSETS IN /public/assets/medieval/buildings/)
  // ==========================================================================
  building_castle_keep: {
    assetId: 'building_castle_keep',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/keep.glb',
    format: 'glb',
    intendedUse: 'Central Sovereign Castle / Keep with multi-tiered towers and battlements',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 5640,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_farm_windmill: {
    assetId: 'building_farm_windmill',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/windmill.glb',
    format: 'glb',
    intendedUse: 'Royal Farmstead with rotating windmill sail mechanism and grain store',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 2780,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_lumber_sawmill: {
    assetId: 'building_lumber_sawmill',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/sawmill.glb',
    format: 'glb',
    intendedUse: 'Lumber Sawmill complex with log chute and timber frame',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 3120,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_stone_quarry: {
    assetId: 'building_stone_quarry',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/quarry.glb',
    format: 'glb',
    intendedUse: 'Stone Quarry mine shaft portal and excavation scaffolding',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 1420,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_barracks_garrison: {
    assetId: 'building_barracks_garrison',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/barracks.glb',
    format: 'glb',
    intendedUse: 'Infantry Barracks garrison quarters and martial muster hall',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 4180,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_infirmary_church: {
    assetId: 'building_infirmary_church',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/infirmary.glb',
    format: 'glb',
    intendedUse: 'Apothecary Infirmary & Sanctuary for healing wounded troops',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 1840,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_academy_observatory: {
    assetId: 'building_academy_observatory',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/academy.glb',
    format: 'glb',
    intendedUse: 'Royal Academy & High Research Observatory tower',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 2810,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_archery_range: {
    assetId: 'building_archery_range',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/archeryrange.glb',
    format: 'glb',
    intendedUse: 'Archery Range practice field and bowyer depot',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 3750,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_blacksmith_hearth: {
    assetId: 'building_blacksmith_hearth',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/blacksmith.glb',
    format: 'glb',
    intendedUse: 'Blacksmith Armory, iron forge, and weapon crafting shop',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 2420,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_house_residence: {
    assetId: 'building_house_residence',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/house.glb',
    format: 'glb',
    intendedUse: 'Civilian timber residence and town quarter habitation',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 1260,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_market_warehouse: {
    assetId: 'building_market_warehouse',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/market.glb',
    format: 'glb',
    intendedUse: 'Royal Treasury & Marketplace warehouse storage hall',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 2900,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  building_gate_portal: {
    assetId: 'building_gate_portal',
    category: 'buildings',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/buildings/gate.glb',
    format: 'glb',
    intendedUse: 'Grand Sovereign Gatehouse gateway portal to world map',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 1140,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },

  // ==========================================================================
  // 2. NATURE & TERRAIN PROPS (/public/assets/medieval/nature/)
  // ==========================================================================
  nature_tree_single: {
    assetId: 'nature_tree_single',
    category: 'environment',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/nature/tree_single.glb',
    format: 'glb',
    intendedUse: 'Stylized coniferous / broadleaf tree for kingdom courtyards',
    performanceTier: 'essential',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 360,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  nature_tree_grove: {
    assetId: 'nature_tree_grove',
    category: 'environment',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/nature/tree_grove.glb',
    format: 'glb',
    intendedUse: 'Dense stylized forest grove cluster for kingdom boundary',
    performanceTier: 'essential',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 1280,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  nature_rock_single: {
    assetId: 'nature_rock_single',
    category: 'environment',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/nature/rock_single.glb',
    format: 'glb',
    intendedUse: 'Granite boulder terrain accent',
    performanceTier: 'essential',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 310,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  nature_rock_cluster: {
    assetId: 'nature_rock_cluster',
    category: 'environment',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/nature/rock_cluster.glb',
    format: 'glb',
    intendedUse: 'Rocky crag outcrop cluster for cliff edges and quarry perimeter',
    performanceTier: 'essential',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0', 'lod1'] },
    triangleCount: 340,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },

  // ==========================================================================
  // 3. KINGDOM PROPS & DETAIL ACCENTS (/public/assets/medieval/props/)
  // ==========================================================================
  prop_crate: {
    assetId: 'prop_crate',
    category: 'environment',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/crate.glb',
    format: 'glb',
    intendedUse: 'Timber cargo crate for warehouse and market stalls',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 420,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  prop_resource_lumber: {
    assetId: 'prop_resource_lumber',
    category: 'resources',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/resource_lumber.glb',
    format: 'glb',
    intendedUse: 'Stacked timber logs for sawmill upgrades',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 510,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  prop_resource_stone: {
    assetId: 'prop_resource_stone',
    category: 'resources',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/resource_stone.glb',
    format: 'glb',
    intendedUse: 'Dressed stone blocks for quarry upgrades',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 480,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  prop_target: {
    assetId: 'prop_target',
    category: 'military',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/target.glb',
    format: 'glb',
    intendedUse: 'Archery straw target for military training ground',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 430,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  prop_weaponrack: {
    assetId: 'prop_weaponrack',
    category: 'military',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/weaponrack.glb',
    format: 'glb',
    intendedUse: 'Timber weapon rack with blades and polearms for barracks yard',
    performanceTier: 'standard',
    instancingEligible: true,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 350,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  prop_tent: {
    assetId: 'prop_tent',
    category: 'military',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/props/tent.glb',
    format: 'glb',
    intendedUse: 'Military pavilion command tent for high-level encampments',
    performanceTier: 'standard',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 420,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },

  // ==========================================================================
  // 4. HERO COMMANDERS (/public/assets/medieval/heroes/)
  // ==========================================================================
  hero_warlord_mesh: {
    assetId: 'hero_warlord_mesh',
    category: 'characters',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/heroes/warlord.glb',
    format: 'glb',
    intendedUse: 'Rigged animated Barbarian / Warlord heavy warrior with battleaxe and pelt',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 4320,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  hero_guardian_mesh: {
    assetId: 'hero_guardian_mesh',
    category: 'characters',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/heroes/guardian.glb',
    format: 'glb',
    intendedUse: 'Rigged animated Knight / Guardian plate armor bastion with sword & shield',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 4410,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  hero_ranger_mesh: {
    assetId: 'hero_ranger_mesh',
    category: 'characters',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/heroes/ranger.glb',
    format: 'glb',
    intendedUse: 'Rigged animated Rogue Scout / Ranger hooded sharpshooter',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 4290,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  hero_steward_mesh: {
    assetId: 'hero_steward_mesh',
    category: 'characters',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/heroes/steward.glb',
    format: 'glb',
    intendedUse: 'Rigged animated Rogue / Steward realm administrator',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 4310,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
  hero_strategist_mesh: {
    assetId: 'hero_strategist_mesh',
    category: 'characters',
    source: 'KayKit (Kay Lousberg)',
    license: 'CC0',
    filePath: '/assets/medieval/heroes/strategist.glb',
    format: 'glb',
    intendedUse: 'Rigged animated Mage / Strategist scholar tactician in flowing robes',
    performanceTier: 'essential',
    instancingEligible: false,
    lodAvailability: { hasLOD: true, availableTiers: ['lod0'] },
    triangleCount: 4280,
    textureResolution: '512x512 atlas (embedded)',
    status: 'active',
  },
};
